---
title: "Untitled"
author: "Claire Madden"
date: "4/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(forcats)

clim <- read_csv("clim_proj.csv")

# highest of projections = rcp 4.5 cool/wet
# lowest of projections = rcp 8.5 compliment

hist <- read_csv("hist_flows.csv") %>% 
  select(year, month, streamflow) %>% 
  mutate(month = factor(month, levels = unique(month)))


```


```{r}

# Organizing (badly) the data to get it ready for plotting

hist_avg <- hist %>%
  filter(year != 1995) %>% 
  group_by(month) %>% 
  summarize(meanflow = mean(streamflow)) 

clim_high_45coolwet <- clim %>% 
  filter(rcp == "rcp45", scenario == "coolwet")

clim_low_85compliment <- clim %>% 
  filter(rcp == "rcp85", scenario == "comp")

clim_low_high <- inner_join(clim_high_45coolwet, clim_low_85compliment, by = "month") %>% 
  mutate(low = streamflow.y) %>% 
  mutate(high = streamflow.x) %>% 
  select(month, low, high) %>% 
  mutate(month = factor(month, levels = unique(month)))

clim_45_high <- clim %>% 
  filter(rcp == "rcp45", scenario == "coolwet") 

clim_45_low <- clim %>% 
  filter(rcp == "rcp45", scenario == "comp") 
  
clim_85_high <- clim %>% 
  filter(rcp == "rcp85", scenario == "coolwet") 

clim_85_low <- clim %>% 
  filter(rcp == "rcp85", scenario == "comp") 

rcp45_ribbon <- inner_join(clim_45_high, clim_45_low, by = "month") %>% 
  mutate(low = streamflow.y) %>% 
  mutate(high = streamflow.x) %>% 
  mutate(month = factor(month, levels = unique(month)))

rcp85_ribbon <- inner_join(clim_85_high, clim_85_low, by = "month") %>% 
  mutate(low = streamflow.y) %>% 
  mutate(high = streamflow.x) %>% 
  mutate(month = factor(month, levels = unique(month)))


```

```{r}
# start putting on a plot (individually first, to make easier to edit, then will pop together)

# historical plot

historical_plot <- ggplot(hist, aes(x = month, y = streamflow, group = year)) +
  geom_line(color = "gray80") +
  theme_minimal()

historical_plot
  
```

```{r}
# historical avg

# historical plot

historical_avg_plot <- ggplot(hist_avg) +
  geom_line(aes(x = month, y = meanflow, group = 1), color = "black", linetype = "dashed") +
  theme_minimal()

historical_avg_plot
```


```{r}
# climate plot

clim_plot_fill <- ggplot(clim_low_high) + 
  geom_line(aes(x = month, y = ((low+high)/2), group = 1), color = "black") +
  geom_ribbon(aes(x=month, ymin = low, ymax = high, group = 1), color = "blue", fill = "blue", alpha = 0.3)

clim_plot_fill

```

```{r}
# putting them all together!
# one climate ribbon

final_plot <- ggplot() +
  geom_line(data = hist, aes(x = month, y = streamflow, group = year), color = "gray75") +
  geom_line(data = hist_avg, aes(x = month, y = meanflow, group = 1), color = "black", linetype = "dashed") +
  geom_ribbon(data = clim_low_high, aes(x=month, ymin = low, ymax = high, group = 1), fill = "blue", alpha = 0.3) +
  theme_minimal()
  
final_plot
  
```

```{r}
# two climate ribbons

final_plot_2 <- ggplot() +
  geom_line(data = hist, aes(x = month, y = streamflow, group = year), color = "gray75") +
  geom_line(data = hist_avg, aes(x = month, y = meanflow, group = 1), color = "black", linetype = "dashed") +
  geom_ribbon(data = rcp45_ribbon, aes(x=month, ymin = low, ymax = high, group = 1), fill = "blue", alpha = 0.5) +
  geom_ribbon(data = rcp85_ribbon, aes(x = month, ymin = low, ymax = high, group = 1), fill = "green", alpha = 0.5) +
  theme_minimal()
  
final_plot_2
```

